export const gameTypes = [
  //{ value: "SKYBLOCK", name: "Skyblock" },
  { value: "BATTLEGROUND", name: "Battleground" },
  { value: "BUILD_BATTLE", name: "Build Battle" },
  { value: "PROTOTYPE", name: "Prototype (Skyblock)" },
  { value: "ARCADE", name: "Arcade" },
  { value: "WOOL_GAMES", name: "Wool Games" },
  { value: "PIT", name: "The Pit" },
  { value: "SPEED_UHC", name: "Speed UHC" },
  { value: "BEDWARS", name: "Bed Wars" },
  { value: "QUAKECRAFT", name: "Quakecraft" },
  { value: "MCGO", name: "MCGO" },
  { value: "WALLS", name: "Walls" },
  { value: "GINGERBREAD", name: "Gingerbread" },
  { value: "HOUSING", name: "Housing" },
  { value: "MURDER_MYSTERY", name: "Murder Mystery" },
  { value: "WALLS3", name: "Walls 3" },
  { value: "SURVIVAL_GAMES", name: "Survival Games" },
  { value: "SUPER_SMASH", name: "Super Smash" },
  { value: "REPLAY", name: "Replay" },
  { value: "SKYWARS", name: "Skywars" },
  { value: "TNTGAMES", name: "TNT Games" },
  { value: "VAMPIREZ", name: "Vampirez" },
  { value: "ARENA", name: "Arena" },
  { value: "DUELS", name: "Duels" },
  { value: "UHC", name: "UHC" },
  { value: "SMP", name: "SMP" },
  { value: "LEGACY", name: "Legacy" },
  { value: "PAINTBALL", name: "Paintball" },
];
